// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Login - Use 'LoginParams' to pass parameters into this method.
        /// </summary>
        public void Login()
        {
            #region Variable Declarations
            HtmlEdit uIUserNameEdit = this.UIArcProLoginInternetEWindow.UIArcProLoginDocument.UIUserNameEdit;
            HtmlEdit uIPasswordEdit = this.UIArcProLoginInternetEWindow.UIArcProLoginDocument.UIPasswordEdit;
            #endregion

            // Type 'milu.mathew@rrd.com' in 'UserName' text box
            uIUserNameEdit.Text = this.LoginParams.UIUserNameEditText;

            // Type '{Tab}' in 'UserName' text box
            Keyboard.SendKeys(uIUserNameEdit, this.LoginParams.UIUserNameEditSendKeys, ModifierKeys.None);

            // The control for this action was not recorded.

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LoginParams.UIPasswordEditPassword;

            // Type '{Enter}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginParams.UIPasswordEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LoginParams.UIPasswordEditPassword1;

            // Type '{Enter}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginParams.UIPasswordEditSendKeys1, ModifierKeys.None);
        }
        
        #region Properties
        public virtual LoginParams LoginParams
        {
            get
            {
                if ((this.mLoginParams == null))
                {
                    this.mLoginParams = new LoginParams();
                }
                return this.mLoginParams;
            }
        }
        
        public UIArcProLoginInternetEWindow UIArcProLoginInternetEWindow
        {
            get
            {
                if ((this.mUIArcProLoginInternetEWindow == null))
                {
                    this.mUIArcProLoginInternetEWindow = new UIArcProLoginInternetEWindow();
                }
                return this.mUIArcProLoginInternetEWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginParams mLoginParams;
        
        private UIArcProLoginInternetEWindow mUIArcProLoginInternetEWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Login'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class LoginParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'milu.mathew@rrd.com' in 'UserName' text box
        /// </summary>
        public string UIUserNameEditText = "milu.mathew@rrd.com";
        
        /// <summary>
        /// Type '{Tab}' in 'UserName' text box
        /// </summary>
        public string UIUserNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "gcIoXr16Z42oXjN0dijMfhiyDunDjWUhiDgTN38+cH4=";
        
        /// <summary>
        /// Type '{Enter}' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword1 = "gcIoXr16Z41n5zUAxnlzyfsnidhc6DEUUJyURBX/YA8=";
        
        /// <summary>
        /// Type '{Enter}' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys1 = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIArcProLoginInternetEWindow : BrowserWindow
    {
        
        public UIArcProLoginInternetEWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "ArcPro - Login";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("ArcPro - Login");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIArcProLoginDocument UIArcProLoginDocument
        {
            get
            {
                if ((this.mUIArcProLoginDocument == null))
                {
                    this.mUIArcProLoginDocument = new UIArcProLoginDocument(this);
                }
                return this.mUIArcProLoginDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIArcProLoginDocument mUIArcProLoginDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIArcProLoginDocument : HtmlDocument
    {
        
        public UIArcProLoginDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "ArcPro - Login";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/adfs/ls/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://testsso1.wip.dfsco.com/adfs/ls/?wa=wsignin1.0&wtrealm=https%3a%2f%2fscpte" +
                "st.dfsco.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fClientSelection.aspx%252f" +
                "&wct=2017-04-06T04%3a45%3a31Z";
            this.WindowTitles.Add("ArcPro - Login");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUserNameEdit
        {
            get
            {
                if ((this.mUIUserNameEdit == null))
                {
                    this.mUIUserNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceHolder1_ctl00_UserName";
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$ctl00$UserName";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "Form";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "tabIndex=1 id=ctl00_ContentPlaceHolder1_";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "9";
                    this.mUIUserNameEdit.WindowTitles.Add("ArcPro - Login");
                    #endregion
                }
                return this.mUIUserNameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceHolder1_ctl00_Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$ctl00$Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "Form";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "tabIndex=2 id=ctl00_ContentPlaceHolder1_";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "10";
                    this.mUIPasswordEdit.WindowTitles.Add("ArcPro - Login");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUserNameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        #endregion
    }
}
